; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD

PUBLIC	main
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+6
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
xdata	SEGMENT
$unwind$main DD	010201H
	DD	07002H
xdata	ENDS
; Function compile flags: /Odtp /RTCsu
; File f:\visualstudioprojects\glm-0.9.8.5\glm\detail\dummy.cpp
_TEXT	SEGMENT
main	PROC

; 190  : {

$LN3:
	push	rdi

; 191  : /*
; 192  : 	glm::vec1 o(1);
; 193  : 	glm::vec2 a(1);
; 194  : 	glm::vec3 b(1);
; 195  : 	glm::vec4 c(1);
; 196  : 
; 197  : 	glm::quat q;
; 198  : 	glm::dualquat p;
; 199  : 
; 200  : 	glm::mat4 m(1);
; 201  : 
; 202  : 	float a0 = normalizeDotA(a, a);
; 203  : 	float b0 = normalizeDotB(b, b);
; 204  : 	float c0 = normalizeDotC(c, c);
; 205  : */
; 206  : 	return 0;

	xor	eax, eax

; 207  : }

	pop	rdi
	ret	0
main	ENDP
_TEXT	ENDS
END
